### ISSUE TITLE
Trigger only available down to minutes

### ISSUE THREAD

**Issue by mattgolding** [elastic/elasticsearch-watcher-net#1]
I am unable to add a seconds trigger.  The lowest I can go down to is Minutes.  Is this planned for a future update?

**Comment by gmarz** [comment]
Hey @mattgolding, apologies for the delayed response.  Yes- we're in the process of upgrading the client to the latest Watcher release, so we'll make sure to include support for this.

**Comment by mattgolding** [comment]
Thanks @gmarz the issue that was posted right after I posted mine is exactly what I am seeing so I will eagerly await the RC version

**Comment by Mpdreamz** [comment]
Not quite RC but we just released `beta2` which brings our .NET integration up to date with watcher GA

https://github.com/elastic/elasticsearch-watcher-net/releases/tag/1.0.0-beta2

Any feedback appreciated!
