### ISSUE TITLE
Search WatchRecord with FieldDescriptors doesn't generate correct JSON

### ISSUE THREAD

**Issue by aochsner** [elastic/elasticsearch-watcher-net#16]
Having a hard time figuring out what's wrong, but can demonstrate:
This works via strings for fields

```
            var result = Client.Search<WatchRecord>(x => x
                .Index(".watch_history-*")
                .AllTypes()
                .Query(q => q
                    .Filtered(f1 => f1
                        .Filter(f2 => f2.Term("watch_id", alertId))))
                .SortDescending("trigger_event.triggered_time"));
```

This does not when using FieldDescriptors

```
            var result = Client.Search<WatchRecord>(x => x
                .Index(".watch_history-*")
                .AllTypes()
                .Query(q => q
                    .Filtered(f1 => f1
                        .Filter(f2 => f2.Term(fd => fd.WatchId, alertId))))
                .SortDescending(fd => fd.TriggerEvent.TriggeredTime));
```

Results in this (camelCased triggerEvent, triggeredTime, and watchId):

```
{
  "sort": [
    {
      "triggerEvent.triggeredTime": {
        "order": "desc"
      }
    }
  ],
  "query": {
    "filtered": {
      "filter": {
        "bool": {
          "must": [
            {
              "term": {
                "watchId": "9f008093-5fc4-4b26-9792-8b60c78812c2"
              }
            }
          ]
        }
      }
    }
  }
}
```

Any thoughts?

**Comment by Mpdreamz** [comment]
This is default NEST behavior, camelCasing field names. You can control this however see e.g:
http://stackoverflow.com/questions/27282865/how-to-disable-camel-casing-elasticsearch-field-names-in-nest

**Comment by aochsner** [comment]
Wait, I'm confused.  I thought the `[JsonProperty]` annotations on WatchRecord (in NEST.Watcher) would drive the serialization.  Is that not the case?

**Comment by Mpdreamz** [comment]
It drives the serialization but not the property name inference :-1: This has been a longstanding nuisance with NEST 1.x that I can't fix without breaking backwards compatibility. 

I opened a PR against 2.0 https://github.com/elastic/elasticsearch-net/pull/1692 to not repeat the same mistake again (this had totally slipped my mind and was not on any of our backlog)
