### ISSUE TITLE
Listing Watches

### ISSUE THREAD

**Issue by DvirL** [elastic/elasticsearch-watcher-net#19]
There is no option to list watches as can be seen in the link below:

https://www.elastic.co/guide/en/watcher/current/listing-watches.html

```
 GET .watches/_search
{
        "fields" : [], 
        "query" : {"match_all" : { } }
}
```

Thanks.

**Comment by aochsner** [comment]
You should be able to just issue a search against the .watches index...

```
            var result = Client.Search<Watch>(x => x
                .Index(".watches")
                .AllTypes()
```
