### ISSUE TITLE
Watcher Put problem webhook and Interval

### ISSUE THREAD

**Issue by damienbod** [elastic/elasticsearch-watcher-net#2]
Hello, thanks for the library.

I'm creating a new watcher in Elasticsearch and 2 things, don't seem to work.

The webhook adds a Request item to the Json body which causes an validation error.
The interval trigger is missing.

Greetings Damien

Here's the Json body which I want to produce:

```
{
  "trigger" : {
    "schedule" : {
      "interval" : "10s"
    }
  },
  "input": {
    "search": {
      "request": {
        "body": {
          "query": {
            "term": {
              "alarmType": {
                "value": "critical"
              }
            }
          }
        }
      }
    }
  },
  "condition": {
    "always": {}
  },
  "actions": {
    "webAction": {
      "webhook": { 
          "port": 5000,
          "host": "localhost",
          "path": "/api/WatcherEvents/CriticalAlarm",
          "method": "post",
          "headers": {
            "Content-Type": "application/json;charset=utf-8"
          },
          "body": "\"{{ctx.payload.hits.total}}\""       
      }
    }
  }
}
```

Here's the NEST watcher code with the 2 problems mentioned above:

```
  var response = client.PutWatch("critical-alarm-watch", p => p
                .Trigger(t => t
                    .Schedule(s => s
                        .Hourly(h => h
                            .Minute(0, 20)
                        )
                    )
                )
                .Input(i => i
                    .Search(s => s
                        .Request(r => r
                            .Body<AlarmMessage>(b => b
                                .Query(q => q.Term(qt => qt.AlarmType, "critical"))
                            )
                        )
                    )
                )
                .Condition(c => c.Always())
                .Actions(a => a.Add("webAction", 
                    new WebhookAction
                    {
                        Request = new WatcherHttpRequest
                        {
                            Method = HttpMethod.Post,
                            Host= "localhost",
                            Port= 5000,
                            Path= "/api/WatcherEvents/CriticalAlarm",
                            Headers= header,
                            Body= "\"{{ctx.payload.hits.total}}\""
                        }
                    }
                ))
```

Greetings Damien

**Comment by Mpdreamz** [comment]
Hey @damienbod which version of watcher are you using? 

We currently only support `beta1` and are working on getting up to date with the GA release.

**Comment by damienbod** [comment]
Hi @Mpdreamz , thanks for your answer.

I'm using  elasticsearch-watcher-1.0.0-rc1.jar

Greetings Damien

**Comment by damienbod** [comment]
Hi Martjin,

Watch Delete would be nice to have in the new version. 

Greetings Damien

**Comment by rashmivkulkarni** [comment]
Hi @Mpdreamz 

Watcher is now GA. Plz install the latest build.  More info here: 
https://www.elastic.co/guide/en/watcher/current/getting-started.html

Watcher delete API permanently removes a watch.
https://www.elastic.co/guide/en/watcher/current/deleting-watches.html

**Comment by gmarz** [comment]
Fixed via 398fcdd47047570b8d4a0dc1c2aad1e0a8374061 and 7762573109b14bc375ec22f981b84a6ad7914f3b

**Comment by Mpdreamz** [comment]
@damienbod we just released `beta2` which brings our .NET integration up to date with watcher GA

https://github.com/elastic/elasticsearch-watcher-net/releases/tag/1.0.0-beta2

Any feedback appreciated!

**Comment by damienbod** [comment]
Thanks

I will try it out at the start of August.

Greetings Damien

**Comment by damienbod** [comment]
Hi @Mpdreamz 
The interval trigger is missing in beta 2

 "trigger" : {
           "schedule" : {
          "interval" : "10s"
           }
         },

greetings Damien

**Comment by damienbod** [comment]
I also have a LicenseExpiredException for watcher, I haven't tested the webhook  yet.

Greetings Damien

**Comment by gmarz** [comment]
Hey @damienbod, support for the interval schedule was [added](https://github.com/elastic/elasticsearch-watcher-net/commit/398fcdd47047570b8d4a0dc1c2aad1e0a8374061) and should be working...

``` csharp
client.PutWatch("my-watch", p => p
    .Trigger(t => t
        .Schedule(s => s
            .Interval("10s")
        )
    )
);
```

**Comment by damienbod** [comment]
Hi @gmarz 
Thanks for your reply.

I don't have this method when using the beta2 NuGet package

Here is my code 
https://github.com/damienbod/AspNet5Watcher/blob/watcherBeta2Test/src/AspNet5Watcher/SearchEngine/SearchRepository.cs

and the package usage:

https://github.com/damienbod/AspNet5Watcher/blob/watcherBeta2Test/src/AspNet5Watcher/project.json

greetings Damien

**Comment by damienbod** [comment]
Hi @gmarz

The problem is not with the NEST.Watcher NuGet package, but with the cache in the ASP.NET 5 NuGet package manager. I deleted this and everything is as you said. I can use the Interval now.

Thanks

greetings Damien

**Comment by Mpdreamz** [comment]
Thats interesting, ASP.NET 5 might have a bug when caching prereleases?

**Comment by damienbod** [comment]
Hi @Mpdreamz 

looks like a NuGet, dnu bug, maybe it just required a dnu restore instead of manually removing the package cache.

Greetings Damien
