### ISSUE TITLE
Trying to add activate/deactivate functionality

### ISSUE THREAD

**Issue by nickelbob** [elastic/elasticsearch-watcher-net#21]
Hi,

I'm trying to add activate/deactivate functionality (https://www.elastic.co/guide/en/watcher/current/api-rest.html#api-rest-activate-watch) to this project and running into a bit of a roadblock. Apparently the Code Generation tools read from a specification folder - 

`private readonly static string _specFolder = @"..\..\..\..\..\..\elasticsearch-watcher\rest-api-spec\api\";`

I can't find this folder or any info on how to create/get it. Is it possible to re-run the code generation stuff for the current version of the Watcher API?

Thanks!
Nick

**Comment by Mpdreamz** [comment]
This is now implemented in the [elasticsearch-net](https://github.com/elastic/elasticsearch-net) repository.
