### ISSUE TITLE
Watcher not working 

### ISSUE THREAD

**Issue by sreejithseradi** [elastic/elasticsearch-watcher-net#22]
1. Below is the watcher config put through sense 

------------------------------------------------------------------------------------------
PUT watcher/watch/Email_watch
{
  "trigger": {
    "schedule": {
      "interval": "1m"
    }
  },
  "input": {
    "search": {
      "request": {
        "indices": "logstash-2017.02.20",
        "body": {
          "size": 0,
          "query": {
            "range": {
              "syslog_sev_level": {
                "lte": "6 "
              }
            }
          }
        }
      }
    }
  },
  "condition": {
    "script": "return ctx.payload.hits.total > 0"
  },
  "actions": {
    "send_email": {
      "throttle_period": "60m",
      "email": {
        "to": "sreejith@XXX.com",
		    "from": "elk-notification@XXX.com",
        "subject": "Syslog_sev_level less than or equal to 5",
        "body": "Syslog_sev_level less than or equal to 5",
        "attachments": {
          "attached_data": {
            "data": {
              "format": "json"
            }
          }
        },
        "priority": "high"
      }
    }
  }
}

------------------------------------------------------------------------------------------

2.  Below is the Curl output 

XXXX@ubuntu:/usr/share/elasticsearch/config$ curl -XGET 'http://localhost:9200/_watcher/stats?pretty'
{
  "watcher_state" : "started",
  "watch_count" : 2,
  "execution_thread_pool" : {
    "queue_size" : 0,
    "max_size" : 15
  },
  "manually_stopped" : false
}

------------------------------------------------------------------------------------------

3. Elasticsearch.yml config

watcher.index.rest.direct_access : true
watcher.actions.email.service.account:
    exchange_account:
        profile: outlook
        email_defaults:
            from: ELK-dc-notiifcations@XXX.com
        smtp:
            auth: false 
            starttls.enable: false 
            host: Smtp.1bank.XXX.com 
            port: 25
            user: ELK-dc-notiifcations@XXX.com 
            password:<no password>

---------------------------------------------------

4. 
Below is the versions  been used ..

Kibana Version 4.5.4
elasticsearch 2.4.2
Logstash 2.3.4
Watcher 2.4.4.

Email for some reason is not been initiated ..Anyone can help if possible

**Comment by russcam** [comment]
@sreejithseradi This repository is for a standalone version of the Watcher APIs that is compatible with NEST 1.x. Since you are using Elasticsearch 2.4.2, you should [use the latest NEST 2.x](https://www.nuget.org/packages/NEST/2.5.2) (currently 2.5.2) which contains the Watcher APIs and is compatible with Elasticsearch 2.4.2 and Watcher 2.4.4.

I'm going to close this issue; if there is an issue with NEST 2.x, [feel free to open a ticket on the NEST github repository.](https://github.com/elastic/elasticsearch-net)
